#!/bin/bash

function create_logrotate_config() {
cat <<EOF > /etc/logrotate.conf
/log/spdk_tgt.log {
    rotate 1
    size 20M
    missingok
    notifempty
    copytruncate
}

/log/instance-manager.log {
    rotate 1
    size 20M
    missingok
    notifempty
    copytruncate
}
EOF
}

# Create logrotate configuration
create_logrotate_config

# Like cron job, run logrotate every 1 minute
while true; do
    sleep 60
    logrotate /etc/logrotate.conf
done &
