#!/bin/bash

function show_help() {
    cat <<EOF
Usage: $0 [OPTIONS]

Options:
    -s, --enable-spdk  Enable SPDK
    -l, --spdk-log     SPDK log level
    -h, --help         Show this help message and exit
EOF
    exit 0
}

function bind_dev() {
    mount --rbind /host/dev /dev
}

function bind_sys() {
    mount --rbind /host/sys /sys
}

function enable_tgtd() {
    echo "Enabling tgtd"
    tgtd -f 2>&1 | tee /var/log/tgtd.log &
}

function enable_spdk_tgt() {
    local options=("$@")
    echo "Enabling spdk_tgt with options: ${options[*]}"
    spdk_tgt "${options[@]}" 2>&1 | tee /var/log/spdk_tgt.log &

    timeout=120  # Timeout in seconds
    interval=1  # Interval in seconds
    elapsed_time=0

    while [ $elapsed_time -lt $timeout ]; do
        if [ -S "/var/tmp/spdk.sock" ]; then
            echo "Socket file '/var/tmp/spdk.sock' found after $elapsed_time seconds."
            return 0  # Exit successfully if the file exists
        fi

        sleep $interval
        elapsed_time=$((elapsed_time + interval))
    done

    echo "Timeout reached. Socket file '/var/tmp/spdk.sock' not found."
    return 1
}

enable_spdk=0
spdk_options=()
instance_manager_options=()

while [[ $# -gt 0 ]]; do
    opt="$1"
    case $opt in
        -s|--enable-spdk)
            enable_spdk=1
            ;;
        -l|--spdk-log)
            spdk_options+=("-L" "$2")
            shift
            ;;
        -h|--help)
            show_help
            ;;
        *)
            instance_manager_options+=("$1")
            ;;
    esac
    shift
done

#### Main ####

bind_dev
bind_sys
enable_tgtd
[ "$enable_spdk" -eq 1 ] && enable_spdk_tgt "${spdk_options[@]}"

exec longhorn-instance-manager "${instance_manager_options[@]}"
